# Generated by Django 3.2.9 on 2022-01-27 10:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('address', models.CharField(max_length=200)),
                ('accountType', models.CharField(max_length=200)),
                ('proffisional', models.CharField(blank=True, max_length=300)),
                ('bio', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.IntegerField(blank=True, default=0)),
                ('birthday', models.DateField(blank=True, default=datetime.datetime.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
