# Generated by Django 3.2.9 on 2022-01-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_aplicant_profile_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicant',
            name='profile_link',
            field=models.CharField(max_length=400),
        ),
    ]
