# Generated by Django 3.2.9 on 2022-01-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220131_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_Tybe',
            field=models.CharField(blank=True, choices=[('employee', 'Emloyee'), ('Business', 'Business')], max_length=50, null=True),
        ),
    ]
