# Generated by Django 3.2.9 on 2022-01-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_account_tybe'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_Id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
