# Generated by Django 3.2.9 on 2022-02-01 08:19

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_business_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='Yashir.png', null=True, upload_to=users.models.upload_user_image),
        ),
    ]
